[build-system]
requires = ["setuptools"]

[project]
name = "stthemes"
authors = [
    {name = "Patrick Garrett", email = "pgarrett@scripps.edu"},
]
version = "0.1.0"

dependencies = [
"streamlit",
]

[tool.setuptools]
package-dir = {"" = "src"}